version: '3.5'
services:
  app:
    build: .
    volumes:
      - ./test/html:/var/www/html:ro
  sut:
    image: alpine:3.11
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - ./test/run_tests.sh:/tmp/run_tests.sh:ro
